var stimuli_variables =
[
                                                              //ADDED NEW STIMULI
     {
    "Target": "3bali",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#in#my#mind",
    },
    {
    "Target": "3balh",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#in#his#mind",
   },
   {
    "Target": "b3dni",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#I#am#still",
  },
  {
    "Target": "b3dch",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#you#are#still(female)",
  },
  {
    "Target": "b3dha",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#she#is#still",
  },
  {
    "Target": "tbain",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#you#want(female)",
  },
  {
    "Target": "yahil",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#child",
  },
  {
    "Target": "yahal",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#children",
  },
  {
    "Target": "bro7i",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#on#my#own",
  },
  {
    "Target": "2bach",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#want#you(female)2",
  },
  {
    "Target": "ybach",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "He#wants#you(female)1",
  },
  {
    "Target": "tbach",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "She#wants#you(female)1",
  },
  {
    "Target": "3yel",
    "Word_Validity": "valid",
    "Target_Word_Length": 4,
    "Target_Gloss": "#then3",
  },
  {
    "Target": "madri",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#don't#know",
  },
  {
    "Target": "wayid",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#a#lot2",
  },
  {
    "Target": "bseer",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#I#will#go1",
  },
  {
    "Target": "weyak",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "with#you(male)2",
  },
  {
    "Target": "wyach",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "with#you(female)1",
  },
  {
    "Target": "wyakm",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "with#you#plural",
  },
  {
    "Target": "yalla",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#let's#go#come#on",
  },
  {
    "Target": "7bait",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#I#loved",
  },
  {
    "Target": "laish",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#why",
  },
  {
    "Target": "b3lmk",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#will#teach#you(male)",
  },
  {
    "Target": "27ena",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "now1",
  },
  {
    "Target": "5watk",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "your(male)#sisters",
  },
  {
    "Target": "2mayh",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "My#mother1",
  },
  {
    "Target": "bndsh",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "we#will#enter",
  },
  {
    "Target": "mdait",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#extended",
  },
  {
    "Target": "3ndch",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "you(female)#have",
  },
  {
    "Target": "8reeb",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "close#soon",
  },
  {
    "Target": "ychof",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "he#sees",
  },
  {
    "Target": "rayal",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "man",
  },
  {
    "Target": "7reem",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "women",
  },
  {
    "Target": "28ool",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#I#say",
  },
  {
    "Target": "y8olk",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#he#tell#you(male)2",
  },
  {
    "Target": "ryoo8",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "breakfast",
  },
  {
    "Target": "7sait",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#sensed",
  },
  {
    "Target": "jabli",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "face#verb(female)",
  },
  {
    "Target": "2brak",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "better#more#blessed",
  },
  {
    "Target": "ynsm3",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "it#could#be#heard",
  },
  {
    "Target": "76ait",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#put",
  },
  {
    "Target": "b36ek",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#will#give#you(male)2",
  },
  {
    "Target": "wrana",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "behind#us",
  },
  {
    "Target": "3yayz",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "old#women",
  },
  {
    "Target": "kaify",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "up#to#me",
  },
  {
    "Target": "3yooz",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "old#woman",
  },
  {
    "Target": "bn6l3",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "we#will#leave",
  },
  {
    "Target": "swait",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#made",
  },
  {
    "Target": "bseer",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#will#go",
  }, //S New Words (5 letter words)                                 SHAHAD HERE           
  {
    "Target": "fdait",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#will#sacrifice#myself",
  },
  {
    "Target": "lgait",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#found",
  },
  {
    "Target": "5bait",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#hid",
  },
  {
    "Target": "bswyh",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#will#do#it",
  },
  {
    "Target": "9otch",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "your#voice",
  },
  {
    "Target": "5aiba",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "oh#my#god",
  },
  {
    "Target": "yt6nz",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "make#fun#of",
  },
  {
    "Target": "8lbch",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "your#heart", //double check
  },
  {
    "Target": "bdait",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#started",
  },
  {
    "Target": "7rait",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#am#starting#to#feel#hot",
  },
  {
    "Target": "ch4ab",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Liar",
  },
  {
    "Target": "3baty",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "my#abaya",
  },
  {
    "Target": "ybany",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "he#wants#me",
  },
  {
    "Target": "m6rsh",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "he#sent",
  },
  {
    "Target": "rmsah",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "the#talk",
  },
  {
    "Target": "3zbah",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "farm",
  },
  {
    "Target": "el7wy",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "the#backyard",
  },
  {
    "Target": "bn5sh",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#will#hide",
  },
  {
    "Target": "dla3'y",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "my#sock",
  },
  {
    "Target": "ra3'oh",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "they#kicked#him#out",
  },
  {
    "Target": "shfek",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "what#is#wrong#with#you",
  },
  {
    "Target": "9obna",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "In#our#direction",
  },
  {
    "Target": "l7afy",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "my#blanket",
  },
  {
    "Target": "mtfyj",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "relaxed",
  },
  {
    "Target": "wnasa",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "fun",
  },
  {
    "Target": "2t7ra",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#thought",
  },
  // End of S New Words                                             SHAHAD HERE
  {
    "Target": "3calr",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "b3pik",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "b3pch",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "b3pha",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "tbwin",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "pahil",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "pahal",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "dalak",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "8itlh",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "bro9i",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "2seth",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "2sath",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "2soth",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "ybawk",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "tsath",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "tsark",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "23bzh",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "23bzi",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "3bzha",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "mardo",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "wazed",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "wazid",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "b4eer",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "leyak",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "pyach",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "lyakm",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "lyahm",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "lyaha",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "peyah",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "feyay",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "chsth",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "chstk",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "chsti",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "87ach",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "sydfo",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "7pait",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "saish",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "b4lmk",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "29ana",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "3watk",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "6nayh",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "unayh",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "mbait",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "33nry",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "3yles",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "yesln",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "yaral",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "6reem",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "mra9b",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "مظفلة",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "علمقة",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "حلثقة",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "دلابة",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "رسالق",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "جلالق",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "ثموني",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "زشاعة",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "ثرارة",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "متانع",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "شنمخب",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "ضروشي",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "خكلون",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "مسشون",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "إظتاع",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "طمازم",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "نهربة",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "مطكول",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "تشكيد",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "إفجاب",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "وثالة",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "نبيجة",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "مسخول",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "تدنوص",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "أجصقة",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "دكيضة",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "كاصمه",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "مشغوع",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "اتباق",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "أسبوت",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "متوسث",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "جينار",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "مباغر",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "شخفية",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "تشكيع",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "ذاثلي",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "تعلكم",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "اتسان",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "بنيسة",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "أعنيس",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "جاكوس",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "طفوصة",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "كياحي",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "تمغال",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "اغتشر",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "جثناء",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "إتذال",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "عرهاق",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "علطقة",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "MSA",
  },
  {
    "Target": "شائبة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "defect;impurity#defects;impurities",
    "Language": "MSA",
  },
  {
    "Target": "نائبة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "vicissitudes",
    "Language": "MSA",
  },
  {
    "Target": "طالبة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "female#student",
    "Language": "MSA",
  },
  {
    "Target": "رائحة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "odor;perfume#odors;perfume",
    "Language": "MSA",
  },
  {
    "Target": "لائحة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "list;table;schedule#tables;schedules",
    "Language": "MSA",
  },
  {
    "Target": "جائحة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "calamity;catastrophe",
    "Language": "MSA",
  },
  {
    "Target": "مسالم",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "peaceful",
    "Language": "MSA",
  },
  {
    "Target": "مقاوم",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "resistor",
    "Language": "MSA",
  },
  {
    "Target": "فائدة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "benefit;use#benefits;uses",
    "Language": "MSA",
  },
  {
    "Target": "مائدة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "table#tables",
    "Language": "MSA",
  },
  {
    "Target": "زائدة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "appendage;appendix",
    "Language": "MSA",
  },
  {
    "Target": "رائدة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Ra'ida",
    "Language": "MSA",
  },
  {
    "Target": "عائدة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "profit",
    "Language": "MSA",
  },
  {
    "Target": "دائرة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "office;bureau;district#offices;bureaus;districts#circles;rings;scopes;circuits",
    "Language": "MSA",
  },
  {
    "Target": "طائرة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "aircraft;airplane",
    "Language": "MSA",
  },
  {
    "Target": "أبقار",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "cows",
    "Language": "MSA",
  },
  {
    "Target": "فئران",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "mice",
    "Language": "MSA",
  },
  {
    "Target": "ثائرة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "tumult;rage",
    "Language": "MSA",
  },
  {
    "Target": "دائري",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "circular;ring-shaped",
    "Language": "MSA",
  },
  {
    "Target": "أعذار",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "excuses",
    "Language": "MSA",
  },
  {
    "Target": "حليبي",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "milky",
    "Language": "MSA",
  },
  {
    "Target": "حسناء",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "beauty#female",
    "Language": "MSA",
  },
  {
    "Target": "بائعة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "seller#female",
    "Language": "MSA",
  },
  {
    "Target": "ضائقة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "crisis;predicament#crises;predicaments",
    "Language": "MSA",
  },
  {
    "Target": "ذائقة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "sense_of_taste",
    "Language": "MSA",
  },
  {
    "Target": "عائلة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "family;household#families;households",
    "Language": "MSA",
  },
  {
    "Target": "عجائب",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "wonders",
    "Language": "MSA",
  },
  {
    "Target": "طاولة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "table",
    "Language": "MSA",
  },
  {
    "Target": "ناقلة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "transporter",
    "Language": "MSA",
  },
  {
    "Target": "صامدة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "steadfast",
    "Language": "MSA",
  },
  {
    "Target": "عائلي",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "family;domestic",
    "Language": "MSA",
  },
  {
    "Target": "سائلي",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "fluidity;liquid_state",
    "Language": "MSA",
  },
  {
    "Target": "قائمة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "support;base#lists;indexes",
    "Language": "MSA",
  },
  {
    "Target": "لائمة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "blame;censure",
    "Language": "MSA",
  },
  {
    "Target": "سائمة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "grazing_freely",
    "Language": "MSA",
  },
  {
    "Target": "أراضي",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "lands",
    "Language": "MSA",
  },
  {
    "Target": "كاتبة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "writer#female",
    "Language": "MSA",
  },
  {
    "Target": "مائية",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "juice;sap",
    "Language": "MSA",
  },
  {
    "Target": "زلزلة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "earthquake",
    "Language": "MSA",
  },
  {
    "Target": "ماعون",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "household#items",
    "Language": "MSA",
  },
  {
    "Target": "ثابتة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "principle;rule#principles;rules;restablished_norms",
    "Language": "MSA",
  },
  {
    "Target": "نابتة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "generation",
    "Language": "MSA",
  },
  {
    "Target": "يابسة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "earth;land;ground;terra_firma",
    "Language": "MSA",
  },
  {
    "Target": "كابسة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "compressor",
    "Language": "MSA",
  },
  {
    "Target": "رابطة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "tie;link#ties;links#leagues;unions",
    "Language": "MSA",
  },
  {
    "Target": "ضابطة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "controlling_device;restraining_order",
    "Language": "MSA",
  },
  {
    "Target": "طابعة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "printer;printing_device#printers;printing_devices",
    "Language": "MSA",
  },
  {
    "Target": "شارقة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Sharjah",
    "Language": "MSA",
  },
  {
    "Target": "طارقة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "misfortunes",
    "Language": "MSA",
  },
  {
    "Target": "خارقة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "supernatural;miracles",
    "Language": "MSA",
  },
  // SHAHAD ARABIC WORDS HERE 
  {
    "Target": "سفينة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "ship",
  },
  {
    "Target": "تلفاز",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "TV",
  },
  {
    "Target": "ذبابة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "a fly",
  },
  {
    "Target": "زرافة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Giraffe",
  },
  {
    "Target": "سيارة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "car",
  },
  {
    "Target": "جبانة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Plane",
  },
  {
    "Target": "طريقة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "way",
  },
  {
    "Target": "مجزرة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "massacre",
  },
  {
    "Target": "فاكهة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "fruit",
  },
  {
    "Target": "فنادق",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "hotels",
  },
  {
    "Target": "ألحان",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "tunes",
  },
  {
    "Target": "أماني",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "wishes",
  },
  {
    "Target": "جزيرة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Island",
  },
  {
    "Target": "بركات",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Blessings",
  },
  {
    "Target": "فاتحة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "the#beginning",
  },
  {
    "Target": "إقليم",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "writer",
  },
  {
    "Target": "إكليل",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "wreath",
  },
  {
    "Target": "قائمة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "List",
  },
  {
    "Target": "سريعة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "fast",
  },
  {
    "Target": "طويلة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "tall",
  },
  {
    "Target": "ثقيلة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "heavy",
  },
  {
    "Target": "يشتعل",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "on#fire",
  },
  {
    "Target": "تدحرج",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "roll",
  },
  {
    "Target": "كواكب",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "planets",
  },
  {
    "Target": "أطباء",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "doctors",
  },
  {
    "Target": "أغنياء",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "rich",
  },
  {
    "Target": "asken",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "domal",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "thint",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "grers",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "yodir",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "thees",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "horsh",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "houle",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "thean",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "athen",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "erery",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "lirry",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "pumee",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "chout",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "hocak",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "wheir",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "firly",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "groue",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "avore",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "alair",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "thout",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "othes",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "spert",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "huing",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "sipel",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "speir",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "clery",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "frips",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "tazis",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "feere",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "horen",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "gorlb",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "theas",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "baran",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "heair",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "irart",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "thage",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "foier",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "yense",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "uncor",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "trild",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "firce",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "daten",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "silld",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "jeeds",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "buind",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "ruint",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "whece",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "siser",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
  },
  {
    "Target": "crash",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "quite",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "alarm",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "alive",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "alone",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "along",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "altar",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "agree",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "anger",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "angle",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "angry",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "areas",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "arise",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "armed",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "aware",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "begin",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "being",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "bench",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "blind",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "bones",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "bored",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "cover",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "cream",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "cried",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "dealt",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "death",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "doing",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "fresh",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "front",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "gains",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "horse",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "hotel",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "ideal",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "image",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "jeans",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "joint",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "kinds",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "knees",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "lower",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "lying",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "makes",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "media",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "match",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "visit",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "vital",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "votes",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "wages",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "waist",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "wrong",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "wrote",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  // Shahad English 
  {
    "Target": "house",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "grape",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "break",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "smile",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "earth",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "queen",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "plant",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "tiger",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "dance",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "sleep",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "music",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "cloud",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "snake",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "brush",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "flame",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "ocean",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "sugar",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "apple",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "lemon",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "knife",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "angel",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "clock",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "fairy",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "ghost",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "space",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "night",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Null",
  },
  {
    "Target": "انطمت",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "she#queitened",
    "Language": "Emirati",
  },
  {
    "Target": "انطمي",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "be#quiet(female)",
    "Language": "Emirati",
  },
  {
    "Target": "ارمسو",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "speak#up",
    "Language": "Emirati",
  },
  {
    "Target": "جبدها",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "her#liver",
    "Language": "Emirati",
  },
  {
    "Target": "شبرية",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#bed",
    "Language": "Emirati",
  },
  {
    "Target": "بلاكم",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#what#is#up#with#you(plural)",
    "Language": "Emirati",
  },
  {
    "Target": "بلاني",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#what#is#up#with#me",
    "Language": "Emirati",
  },
  {
    "Target": "بلاهم",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#what#is#up#with#them",
    "Language": "Emirati",
  },
  {
    "Target": "انتوا",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#you(plural)",
    "Language": "Emirati",
  },
  {
    "Target": "انزين",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#alright",
    "Language": "Emirati",
  },
  {
    "Target": "قلتله",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#I#said#to#him",
    "Language": "Emirati",
  },
  {
    "Target": "اوكيه",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "ok2",
    "Language": "Emirati",
  },
  {
    "Target": "شراتج",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "like#you#female",
    "Language": "Emirati",
  },
  {
    "Target": "خلاني",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#leave#me",
    "Language": "Emirati",
  },
  {
    "Target": "عنفسي",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#on#myself",
    "Language": "Emirati",
  },
  {
    "Target": "سرينا",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "we#left",
    "Language": "Emirati",
  },
  {
    "Target": "عيبني",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "i#liked#it",
    "Language": "Emirati",
  },
  {
    "Target": "مادري",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#don't#know",
    "Language": "Emirati",
  },
  {
    "Target": "وياكم",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "with#you(plural)1",
    "Language": "Emirati",
  },
  {
    "Target": "وياهم",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "with#them1",
    "Language": "Emirati",
  },
  {
    "Target": "وياها",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "with#her1",
    "Language": "Emirati",
  },
  {
    "Target": "جفتها",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "i#saw#her",
    "Language": "Emirati",
  },
  {
    "Target": "بعطيج",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#will#give#you(female)",
    "Language": "Emirati",
  },
  {
    "Target": "يعطيج",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "He#gives#you(female)",
    "Language": "Emirati",
  },
  {
    "Target": "تعطيج",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "She#gives#you(female)",
    "Language": "Emirati",
  },
  {
    "Target": "اعطيج",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#give#you(female)",
    "Language": "Emirati",
  },
  {
    "Target": "عطيتج",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#gave#you(female)",
    "Language": "Emirati",
  },
  {
    "Target": "اهلين",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#hello3",
    "Language": "Emirati",
  },
  {
    "Target": "حبيته",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#I#loved#him",
    "Language": "Emirati",
  },
  {
    "Target": "يبونك",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#they#want#you(male)",
    "Language": "Emirati",
  },
  {
    "Target": "يبونج",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#they#want#you(female)",
    "Language": "Emirati",
  },
  {
    "Target": "بعلمج",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#will#teach#you(female)",
    "Language": "Emirati",
  },
  {
    "Target": "بعلمك",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#will#teach#you(male)",
    "Language": "Emirati",
  },
  {
    "Target": "احينه",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "now1",
    "Language": "Emirati",
  },
  {
    "Target": "كشختي",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#my#fancy#look1",
    "Language": "Emirati",
  },
  {
    "Target": "خواتك",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "your(male)#sisters",
    "Language": "Emirati",
  },
  {
    "Target": "خواتج",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "your(female)#sisters",
    "Language": "Emirati",
  },
  {
    "Target": "وناسة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "happiness#joy#fun",
    "Language": "Emirati",
  },
  {
    "Target": "امايه",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "My#mother",
    "Language": "Emirati",
  },
  {
    "Target": "ععمري",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "on#my#life#on#my#age",
    "Language": "Emirati",
  },
  {
    "Target": "طشونة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#a#bit",
    "Language": "Emirati",
  },
  {
    "Target": "يلسوا",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "sit(plural_male)",
    "Language": "Emirati",
  },
  {
    "Target": "دريشة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "window",
    "Language": "Emirati",
  },
  {
    "Target": "ريايل",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "men",
    "Language": "Emirati",
  },
  {
    "Target": "مراحب",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "welcomes#hellos",
    "Language": "Emirati",
  },
  {
    "Target": "اقولج",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#I#tell#you(female)",
    "Language": "Emirati",
  },
  {
    "Target": "اقولك",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#I#tell#you(male)",
    "Language": "Emirati",
  },
  {
    "Target": "يقولج",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#He#tells#you(female)",
    "Language": "Emirati",
  },
  {
    "Target": "تقولج",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "#She#tells#you(female)",
    "Language": "Emirati",
  },
  {
    "Target": "عبالي",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "driver",
  },
  {
    "Target": "لقافة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "curious",
  },
  {
    "Target": "عبالك",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "okay",
  },
  {
    "Target": "غمضني",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#pity#him",
  },
  {
    "Target": "متروس",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "full",
  },
  {
    "Target": "مزيون",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "handsome",
  },
  {
    "Target": "حذالي",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "next#to#me",
  },
  {
    "Target": "مندوس",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "wooden#box",
  },
  {
    "Target": "شغابي",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "my#earring",
  },
  {
    "Target": "شباصه",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "hair#clip",
  },
  {
    "Target": "بيزات",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "money",
  },
  {
    "Target": "زولية",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "carpet",
  },
  {
    "Target": "دفاشة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "reckless",
  },
  {
    "Target": "زيغني",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "he#scared#me",
  },
  {
    "Target": "برنوص",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "blanket",
  },
  {
    "Target": "فوالة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "hospitality",
  },
  {
    "Target": "عكيفج",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "It#is#not#up#to#you",
  },
  {
    "Target": "انزخ",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "he#was#caught",
  },
  {
    "Target": "أواجع",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "I#scold",
  },
  {
    "Target": "خقاقة",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "narcissist",
  },
  {
    "Target": "غرشتي",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "my#bottle",
  },
  {
    "Target": "مجبوس",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "Machboos", // check
  },
  {
    "Target": "حِياتي",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "my#brows",
  },
  {
    "Target": "سامان",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "stuff",
  },
  {
    "Target": "عبالج",
    "Word_Validity": "valid",
    "Target_Word_Length": 5,
    "Target_Gloss": "you(female)#thought",
  },
  {
    "Target": "اسعند",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "انظقت",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "انظقي",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "هاغات",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "خبدها",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "فبرية",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "ظلاكم",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "ظلاني",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "ظلاهم",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "اقتوا",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "ابزين",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "فلبله",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "ارطيه",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "ثراسي",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "خلامي",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "عفتسي",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "سزينا",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "عشلها",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "ماذري",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "زماكم",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "زماهم",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "زماها",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "خثفها",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "بضطيج",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "يضطيج",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "تضطيج",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "اضطيج",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "اغلين",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "حتتنه",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "بثونك",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "بثونج",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "عبلمج",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "عبلمك",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "اخينه",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "كخشتو",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "جطاتك",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "حواتج",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "وناشة",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "اثايه",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "عغمري",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "ظشونة",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "تلسوا",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "بتلسن",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "ربايل",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "مزاحب",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "اضولج",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "اضولك",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "يضولج",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "تضولج",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  },
  {
    "Target": "يضولج",
    "Word_Validity": "invalid",
    "Target_Word_Length": 5,
    "Target_Gloss": "nonword",
    "Language": "Emirati",
  }
]
